Java plugin reuse features
- functions for use in control scripts
- function for locating java plugin dir during setup

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -2,6 +2,19 @@
 
 . "$genapp_functions/core"
 
+java_plugin_dir() {
+    _local_jar=$plugin_dir/lib/genapp-java.jar
+    _java_embedded_jar=$plugin_dir/java/lib/genapp-java.jar
+    if [ -e $plugin_dir/lib/genapp-java.jar ]; then
+	echo $plugin_dir
+    elif [ -e $plugin_dir/java/lib/genapp-java.jar ]; then
+	echo $plugin_dir/java
+    else
+	echo "Cannot find java plugin dir in $plugin_dir" 1>&2
+	return 1
+    fi
+}
+
 find_java() {
     _version=$(metadata java_version "1.7")
     case "$_version" in
@@ -14,6 +27,12 @@ find_java() {
 	    return 1
 	    ;;
     esac
+}
+
+install_java_control_functions() {
+    _plugin_dir=$(java_plugin_dir)
+    mkdir -p $control_dir/java
+    cp $_plugin_dir/control/functions $control_dir/java/functions
 }
 
 install_app() {
@@ -47,16 +66,8 @@ java_classpath() {
 }
 
 find_agent_jar() {
-    _local_jar=$plugin_dir/lib/genapp-java.jar
-    _java_embedded_jar=$plugin_dir/java/lib/genapp-java.jar
-    if [ -e $_local_jar ]; then
-	echo $_local_jar
-    elif [ -e $_java_embedded_jar ]; then
-	echo $_java_embedded_jar
-    else
-	echo "Cannot find agent jar in $plugin_dir" 1>&2
-	return 1
-    fi
+    _plugin_dir=$(java_plugin_dir)
+    echo $_plugin_dir/lib/genapp-java.jar
 }
 
 install_java_agent() {
